Repository jeff-rey-wang/utrition, pull requests merged in 2022-11, with the labels that each got.

#110 FR Tests
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#111 Adding functional requirement system tests
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#112 Completed Plan Section
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#114 still requires references
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#115 VNVPlan - Nonfunctional Unit Tests
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#118 Updated Dev Plan to add testing framework
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/DevelopmentPlan/DevelopmentPlan.tex
Labels: documentation

#120 Finished Reflection Appendix Part and Added Sections Template
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#119 VNV: Adding requirements traceability
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#117 ref done
  docs/VnVPlan/VnVPlan.tex
  refs/References.bib
Labels: documentation

#121 VNV: Reflection section structure and my reflection
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#122 VNV Reflection - Jeffrey
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#124 VnV - added trace matrix for unit test FR
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#125 added reflection in appendix
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#126 fixed proof of concept and added reflecs
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#127 VNV Test Revision
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#128 done objectives
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#129 Review of VnV Plan
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  test/testPhotos/chair.jpg
  test/testPhotos/hello.txt
Labels: documentation

#136 POC - Create Initial React Application
  src/utrition/.gitignore
  src/utrition/README.md
  src/utrition/package-lock.json
  src/utrition/package.json
  src/utrition/public/favicon.ico
  src/utrition/public/index.html
  src/utrition/public/logo192.png
  src/utrition/public/logo512.png
  src/utrition/public/manifest.json
  src/utrition/public/robots.txt
  src/utrition/src/App.css
  src/utrition/src/App.js
  src/utrition/src/App.test.js
  src/utrition/src/index.css
  src/utrition/src/index.js
  src/utrition/src/logo.svg
  src/utrition/src/reportWebVitals.js
  src/utrition/src/setupTests.js
Labels: frontend

#144 POC - FE: Adding Navbar
  src/utrition/package-lock.json
  src/utrition/package.json
  src/utrition/src/App.css
  src/utrition/src/App.js
  src/utrition/src/components/navbar/index.js
  src/utrition/src/components/navbar/navbarElements.js
  src/utrition/src/index.css
  src/utrition/src/index.js
  src/utrition/src/logo.svg
  src/utrition/src/pages/index.js
  src/utrition/src/pages/profile_page.js
  src/utrition/src/pages/upload_page.js
Labels: frontend

#145 POC: backend-frontend communication
  src/POC/POC.py
  src/POC/home/__init__.py
  src/POC/home/__init__.pyc
  src/POC/home/views.py
  src/POC/home/views.pyc
  src/POC/settingslocal.py
  src/POC/static/css/index.css
  src/POC/static/js/index.js
  src/POC/templates/index.html
  src/utrition-backend/__pycache__/DataHandler.cpython-38.pyc
  src/utrition-backend/__pycache__/MainML.cpython-38.pyc
  src/utrition-backend/userIcon.jpg
Labels: backend

#147 POC-FE: Created Upload Page
  src/utrition/package-lock.json
  src/utrition/package.json
  src/utrition/src/components/imageupload/index.js
  src/utrition/src/pages/upload_page.js
Labels: frontend

#146 Testing nutritionix api endpoints
  src/test_nutritionix.py
Labels: backend

#150 POC: integrating ML model with flask
  src/POC/home/__init__.pyc
  src/POC/home/views.py
  src/POC/home/views.pyc
  src/POC/static/js/index.js
  src/POC/templates/index.html
  src/utrition-backend/Interface.py
  src/utrition-backend/ML/DataHandler.py
  src/utrition-backend/ML/Interface.py
  src/utrition-backend/ML/MainML.py
  src/utrition-backend/ML/__pycache__/DataHandler.cpython-38.pyc
  src/utrition-backend/ML/__pycache__/Interface.cpython-38.pyc
  src/utrition-backend/ML/__pycache__/MainML.cpython-38.pyc
  src/utrition-backend/ML/apple.jpeg
  src/utrition-backend/ML/cifar-100-python/.gitattributes
  src/utrition-backend/ML/cifar-100-python/file.txt~
  src/utrition-backend/ML/cifar-100-python/meta
  src/utrition-backend/ML/cifar-100-python/test
  src/utrition-backend/ML/cifar-100-python/train
  src/utrition-backend/ML/mushroom.jpeg
  src/utrition-backend/ML/pear.jpeg
  src/utrition-backend/ML/sweet_pepper.jpeg
  src/utrition-backend/ML/userIcon.jpg
  src/utrition-backend/POC.py
  src/utrition-backend/__pycache__/DataHandler.cpython-38.pyc
  src/utrition-backend/__pycache__/MainML.cpython-38.pyc
  src/utrition-backend/home/__init__.py
  src/utrition-backend/home/__init__.pyc
  src/utrition-backend/home/__pycache__/__init__.cpython-38.pyc
  src/utrition-backend/home/__pycache__/views.cpython-38.pyc
  src/utrition-backend/home/views.py
  src/utrition-backend/home/views.pyc
  src/utrition-backend/settingslocal.py
  src/utrition-backend/static/css/index.css
  src/utrition-backend/static/js/index.js
  src/utrition-backend/templates/index.html
Labels: backend

#155 POC: Add pyc gitignore, remove old code
  src/utrition/.gitignore
  src/utrition/src/components/imageupload/index.js
  src/utrition/utrition-backend/ML/__pycache__/DataHandler.cpython-310.pyc
  src/utrition/utrition-backend/ML/__pycache__/DataHandler.cpython-38.pyc
  src/utrition/utrition-backend/ML/__pycache__/Interface.cpython-310.pyc
  src/utrition/utrition-backend/ML/__pycache__/Interface.cpython-38.pyc
  src/utrition/utrition-backend/ML/__pycache__/MainML.cpython-310.pyc
  src/utrition/utrition-backend/ML/__pycache__/MainML.cpython-38.pyc
  src/utrition/utrition-backend/home/__pycache__/__init__.cpython-310.pyc
  src/utrition/utrition-backend/home/__pycache__/__init__.cpython-38.pyc
  src/utrition/utrition-backend/home/__pycache__/views.cpython-310.pyc
  src/utrition/utrition-backend/home/__pycache__/views.cpython-38.pyc
  src/utrition/utrition-backend/userIcon.jpg
Labels: backend

#156 call nutritionix api and display info to frontend
  src/utrition/src/App.js
  src/utrition/src/components/imageupload/index.js
  src/utrition/utrition-backend/home/views.py
Labels: backend

#157 Centered Upload Text
  src/utrition/src/pages/upload_page.js
Labels: frontend
