Repository jeff-rey-wang/utrition, pull requests merged in 2023-03, with the labels that each got.

#253 Adding pylint and pytest
  .github/workflows/run-actions.yml
  .gitignore
  pyproject.toml
  src/test_nutritionix.py
  src/utrition/src/tests/backend/test_feature.py
  src/utrition/utrition-backend/ML/DataHandler.py
  src/utrition/utrition-backend/ML/Interface.py
  src/utrition/utrition-backend/ML/MainML.py
  src/utrition/utrition-backend/POC.py
  src/utrition/utrition-backend/home/nutritionalDataFetcher.py
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
  src/utrition/utrition-backend/settingslocal.py
Labels: backend

#256 Backend VnV testing
  .github/workflows/run-actions.yml
  pyproject.toml
  src/utrition/src/tests/backend/test_CSV_operations.py
  src/utrition/src/tests/backend/test_accepted_image_formats_return_data.py
  src/utrition/src/tests/backend/test_current_nutrition.py
  src/utrition/src/tests/backend/test_feature.py
  src/utrition/src/tests/backend/test_input_data_formats.py
  src/utrition/src/tests/backend/test_return_JSON_from_string.py
  src/utrition/utrition-backend/ML/DataHandler.py
Labels: backend

#267 Usability Testing Information for VnV Report
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.tex
Labels: documentation

#268 VnVReport - NFR Evaluation
  docs/VnVReport/VnVReport.tex
Labels: documentation

#269 Vn v report jack
  docs/VnVReport/VnVReport.tex
Labels: documentation

#270 Frontendvnvreport
  docs/VnVReport/VnVReport.tex
  src/utrition/src/components/textupload/testingupload.js
Labels: documentation

#271 VnV Report: Backend & Coverage
  docs/VnVReport/VnVReport.tex
  src/utrition/src/tests/backend/test_input_data_formats.py
Labels: documentation

#272 Jack vn v report plan
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.tex
Labels: documentation

#274 VnVPlan Backend Edits
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#273 Traceability for Requirements
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.tex
Labels: documentation

#275 added new FRs and removed old ones
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#276 reflection done
  docs/VnVReport/VnVReport.tex
Labels: documentation

#277 VNVReport - Changes to the MIS/MG
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#278 changed one-upload-3 and 4 to 1 and 2, updated blurbs in vnvplan
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.tex
Labels: documentation

#279 VnVReport - added unit testing section
  docs/VnVReport/VnVReport.tex
Labels: documentation

#280 Finished Requirements Trace
  docs/VnVReport/VnVReport.tex
Labels: documentation

#281 introduction added
  docs/VnVReport/VnVReport.tex
Labels: documentation

#283 VNVReport - Trace to Modules
  docs/VnVReport/VnVReport.tex
Labels: documentation

#284 Review VnV Report
  docs/SRS/SRS.pdf
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#292 Global Image Upload
  src/utrition/.gitignore
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/utrition-backend/home/views.py
Labels: backend

#291 Add message for invalid input, and some error handling in backend
  src/utrition/src/components/textupload/textupload.js
  src/utrition/src/components/voiceupload/voiceupload.js
  src/utrition/utrition-backend/home/nutritionalDataFetcher.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#294 Added bmi page and bmi button to profile
  src/utrition/src/App.js
  src/utrition/src/pages/BMI_page.css
  src/utrition/src/pages/BMI_page.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#295 Added delete button, prettied up the bmi page
  src/utrition/src/pages/BMI_page.css
  src/utrition/src/pages/BMI_page.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#296 Working logic for POST request in BMI page
  src/utrition/src/pages/BMI_page.js
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend, frontend

#297 Delete Functionality for Backend
  src/utrition/src/pages/profile_page.js
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#299 big huge commit of new settings page, bmi page , profile page
  src/utrition/src/App.js
  src/utrition/src/components/navbar/navbar.js
  src/utrition/src/pages/BMI_page.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
  src/utrition/src/pages/settings_page.css
  src/utrition/src/pages/settings_page.js
Labels: frontend

#298 Added time entry to CSV. Can be called in profile
  src/utrition/src/pages/profile_page.js
  src/utrition/src/tests/backend/test_CSV_operations.py
  src/utrition/utrition-backend/home/profileData.py
Labels: backend

#300 GET request for settings page
  src/utrition/src/pages/BMI_page.js
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#301 Adding Graph
  src/utrition/.gitignore
  src/utrition/src/tests/backend/test_accepted_image_formats_return_data.py
  src/utrition/src/tests/backend/test_current_nutrition.py
  src/utrition/src/tests/backend/test_input_data_formats.py
  src/utrition/utrition-backend/home/views.py
  src/utrition/utrition-backend/user.json
Labels: backend

#302 settings page completed
  src/utrition/src/pages/BMI_page.js
  src/utrition/src/pages/settings_page.css
  src/utrition/src/pages/settings_page.js
  src/utrition/utrition-backend/home/profileData.py
Labels: frontend

#303 added time
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#254 test on alternate machine
  src/node_modules/.package-lock.json
  src/utrition/src/App.test.js
  src/utrition/src/pages/index.test.js
  src/utrition/src/pages/upload_page.js
  src/utrition/src/pages/upload_page.test.js
Labels: frontend

#304 hopefully fixes post req not sending all the time
  src/utrition/src/pages/BMI_page.js
Labels: frontend

#305 Added functionality to edit settings page
  src/utrition/src/pages/BMI_page.js
Labels: frontend

#307 Graph changes
  src/utrition/.gitignore
  src/utrition/utrition-backend/home/views.py
Labels: backend

#310 Rev1 - VoiceUpload - Reset/Submit now clears text
  src/utrition/src/components/voiceupload/voiceupload.js
Labels: frontend

#306 Rev1 TextUpload, Submit on ENTER
  src/utrition/src/components/textupload/textupload.css
  src/utrition/src/components/textupload/textupload.js
Labels: frontend

#309 added graph to profile page
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#308 Made pages prettier and moved stuff
  src/utrition/src/pages/BMI_page.css
  src/utrition/src/pages/BMI_page.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
  src/utrition/src/pages/settings_page.css
  src/utrition/src/pages/settings_page.js
Labels: frontend

#313 Rev1 - Upload Components - Adding units to response
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/src/components/textupload/textupload.js
  src/utrition/src/components/voiceupload/voiceupload.js
Labels: frontend

#312 Rev1 - UploadContainer - Reset upload component on switch
  src/utrition/src/components/uploadcontainer/uploadcontainer.js
Labels: frontend

#314 Rev1 - VoiceUpload - Stopping recording upon switching upload component
  src/utrition/src/components/voiceupload/voiceupload.js
Labels: frontend

#311 Revoneyasmine - all rev one changes added
  src/utrition/src/pages/index.css
  src/utrition/src/pages/index.js
  src/utrition/src/pages/leftarrow.png
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
  src/utrition/src/pages/rightarrow.png
Labels: frontend

#315 made orange box thicker
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#316 Rev1 - ImageUpload - Adding Image Confirmation
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/src/components/voiceupload/voiceupload.js
Labels: frontend

#317 Backend required for deleting entry if image upload is incorrect
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/src/pages/data_graph.png
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#319 colour changes
  src/utrition/src/pages/index.js
  src/utrition/src/pages/profile_page.css
Labels: frontend

#320 Changed error text
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/src/pages/index.js
Labels: frontend

#321 Moved graph creation
  src/utrition/utrition-backend/home/views.py
Labels: backend
