Repository jeff-rey-wang/utrition, pull requests merged in 2023-01, with the labels that each got.

#160 Adding new FRs to project docs
  docs/SRS/SRS.tex
Labels: documentation

#162 Marked unnecessary sections of System Design Document
  docs/Design/SystDesign/SystDes.tex
Labels: documentation

#161 Move function to get nutrition data to separate module
  src/utrition/utrition-backend/home/nutritionalDataFetcher.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#189 MG - Anticipated Changes, Unlikely Changes, Module Hierarchy, Traceability
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftArchitecture/use_hierarchy.png
Labels: documentation

#186 MG Section for modules 8,14, and 15
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#188 Reformatting Section, Adding System Purpose
  docs/Design/SystDesign/SystDes.tex
Labels: documentation

#187 Small code changes, updating module names, removed extraneous code
  src/utrition/src/components/apiService/index.js
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/src/components/imageupload/index.js
  src/utrition/src/components/navbar/navbar.js
Labels: frontend

#191 Design Document - MG - Added Modules 1,5,6,9,10
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#193 merge modules!
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#190 mg minus imprement notes
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#201 Mg decomposition completed
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SystDesign/SystDes.tex
  docs/Design/SystDesign/componentdiagram.jpg
Labels: documentation

#203 MIS: Adding modules 7, 11, 12, 13
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#207 Update MG.tex
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#204 System design
  .github/workflows/run-actions.yml
  docs/Design/SystDesign/Communication_Protocols.png
  docs/Design/SystDesign/SystDes.tex
  docs/Design/SystDesign/System_Context_Diagram.png
Labels: documentation

#212 Stuff from other PR
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#205 sketches added
  docs/Design/SystDesign/SystDes.tex
  docs/Design/SystDesign/home.jpg
  docs/Design/SystDesign/profile.jpg
  docs/Design/SystDesign/upload.jpg
Labels: documentation

#214 update MG with Food Entry Module
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftArchitecture/use_hierarchy.png
Labels: documentation

#213 Remove wss from modules
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#215 finished MIS front end modules
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#217 Design - MIS - Modules 1, 5, 6, 9, 10
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#216 Added Timeline
  docs/Design/SystDesign/SystDes.tex
Labels: documentation

#200 Updated Path names for import statements
  src/utrition/src/App.js
  src/utrition/src/pages/upload_page.js
Labels: bug, frontend

#220 Reviewed Design Documents
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/Design/SystDesign/SystDes.pdf
  docs/Design/SystDesign/SystDes.tex
Labels: documentation

#221 Rev0: CSV Creation & Appending
  src/utrition/.gitignore
  src/utrition/utrition-backend/home/nutritionalDataFetcher.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#228 Rev0 - Basic Voice Recognition Functionality
  src/utrition/package-lock.json
  src/utrition/package.json
  src/utrition/src/components/voiceupload/voiceupload.js
  src/utrition/src/components/voiceupload/voiceuploadElements.js
  src/utrition/src/pages/upload_page.js
Labels: frontend

#231 margins fixed
  src/utrition/src/pages/homefood.jpg
  src/utrition/src/pages/index.js
Labels: frontend

#230 Added basis for profile page and updated styling for navbar to match new styling
  src/utrition/src/components/navbar/navbarElements.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/profile_page.js
Labels: frontend

#229 Backend Calculations for Profile Page
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#232 Rev 0: ManualUpload basic functionality
  src/utrition/src/components/manualupload/manualupload.js
  src/utrition/src/components/manualupload/manualuploadElements.js
  src/utrition/src/pages/profile_page.css
  src/utrition/src/pages/upload_page.css
  src/utrition/src/pages/upload_page.js
Labels: frontend

#233 Update nutritionalDataFetcher for multiple food items, add serving unit/weight
  src/utrition/utrition-backend/home/nutritionalDataFetcher.py
Labels: backend

#234 Formatting JSON for Profile Page
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend

#235 Changed info in json, added total calculation nutrients with multiple input foods and fixed image upload nutrients display
  src/utrition/src/components/imageupload/imageupload.js
  src/utrition/utrition-backend/home/profileData.py
  src/utrition/utrition-backend/home/views.py
Labels: backend
